# Generated by Django 6.0.6 on 2026-06-29 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='college',
            field=models.CharField(default='\x0eot Provided', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='phone',
            field=models.CharField(default='Not Provided', max_length=15),
            preserve_default=False,
        ),
    ]
