# Generated by Django 6.0.6 on 2026-06-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('workshop', 'Workshop'), ('seminar', 'Seminar'), ('tech', 'Tech')], default='tech', max_length=20),
        ),
    ]
